build-linux:
	flutter build linux

build-windows:
	flutter build windows

run-linux:
	flutter run -d linux

run-windows:
	flutter run -d windows

clean:
	flutter clean
	flutter pub get

deps:
	flutter pub get

lint:
	flutter analyze

.PHONY: build-linux build-windows run-linux run-windows clean deps lint
